repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-byte-order-marker
      - id: debug-statements
        language_version: python3.6
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.8.0
        args: ["--ignore=E402,F403,F405,F811,W503"]
        exclude: >
          (?x)^(
          alembic/.+ | features/.+
          )$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args:
          [--ignore-missing-imports, --follow-imports=skip, --strict-optional]
        exclude: >
          (?x)^(
          features/.+
          )$
